<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_sertifikat_model extends CI_Model
{

    public $table = 'tbl_sertifikat';
    public $id = 'id_sertifikat';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->join('tbl_kapal', 'tbl_kapal.id_kapal = tbl_sertifikat.id_kapal');
        return $this->db->get($this->table)->result();
    }

    function get_all_expired()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->join('tbl_kapal', 'tbl_kapal.id_kapal = tbl_sertifikat.id_kapal');
        $this->db->where('tanggal_expired < CURRENT_DATE()');
        return $this->db->get($this->table)->result();
    }

    function count_expired()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->join('tbl_kapal', 'tbl_kapal.id_kapal = tbl_sertifikat.id_kapal');
        $this->db->where('tanggal_expired < CURRENT_DATE()');
        return $this->db->get($this->table)->num_rows();
    }

    function count_belum()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->join('tbl_kapal', 'tbl_kapal.id_kapal = tbl_sertifikat.id_kapal');
        $this->db->where('tanggal_expired >= CURRENT_DATE()');
        return $this->db->get($this->table)->num_rows();
    }

    function get_all_belum()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->join('tbl_kapal', 'tbl_kapal.id_kapal = tbl_sertifikat.id_kapal');
        $this->db->where('tanggal_expired >= CURRENT_DATE()');
        return $this->db->get($this->table)->result();
    }


    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->join('tbl_kapal', 'tbl_kapal.id_kapal = tbl_sertifikat.id_kapal');
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_sertifikat', $q);
        $this->db->or_like('id_kapal', $q);
        $this->db->or_like('tempat_pendaftaran', $q);
        $this->db->or_like('tanda_pendaftaran', $q);
        $this->db->or_like('tanggal_terbit', $q);
        $this->db->or_like('pembaruan_terakhir', $q);
        $this->db->or_like('tanggal_expired', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_sertifikat', $q);
        $this->db->or_like('id_kapal', $q);
        $this->db->or_like('tempat_pendaftaran', $q);
        $this->db->or_like('tanda_pendaftaran', $q);
        $this->db->or_like('tanggal_terbit', $q);
        $this->db->or_like('pembaruan_terakhir', $q);
        $this->db->or_like('tanggal_expired', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_sertifikat_model.php */
/* Location: ./application/models/Tbl_sertifikat_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2025-01-24 06:59:26 */
/* http://harviacode.com */