<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_kapal_model extends CI_Model
{

    public $table = 'tbl_kapal';
    public $id = 'id_kapal';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_kapal', $q);
	$this->db->or_like('nama_kapal', $q);
	$this->db->or_like('tanda_panggilan', $q);
	$this->db->or_like('panjang', $q);
	$this->db->or_like('lebar', $q);
	$this->db->or_like('dimensi', $q);
	$this->db->or_like('tonase_kotor', $q);
	$this->db->or_like('tonase_bersih', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('nomer_imo', $q);
	$this->db->or_like('penggerak_utama', $q);
	$this->db->or_like('merek_tk', $q);
	$this->db->or_like('bahan_utama', $q);
	$this->db->or_like('jumlah_geladak', $q);
	$this->db->or_like('jumlah_baling', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_kapal', $q);
	$this->db->or_like('nama_kapal', $q);
	$this->db->or_like('tanda_panggilan', $q);
	$this->db->or_like('panjang', $q);
	$this->db->or_like('lebar', $q);
	$this->db->or_like('dimensi', $q);
	$this->db->or_like('tonase_kotor', $q);
	$this->db->or_like('tonase_bersih', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('nomer_imo', $q);
	$this->db->or_like('penggerak_utama', $q);
	$this->db->or_like('merek_tk', $q);
	$this->db->or_like('bahan_utama', $q);
	$this->db->or_like('jumlah_geladak', $q);
	$this->db->or_like('jumlah_baling', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_kapal_model.php */
/* Location: ./application/models/Tbl_kapal_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2025-01-24 06:30:51 */
/* http://harviacode.com */